const projects = [
  {
    name: 'Coingeckos price API to Oracle',
    href: '#',
    siteHref: '#',
    repoHref: '#',
    repo: 'gelato/wftoracle6',
    tech: 'Web3 function',
    lastDeploy: '3h ago',
    location: 'United states',
    starred: true,
    active: true,
  },
  {
    name: 'Coingeckos price API to Oracle',
    href: '#',
    siteHref: '#',
    repoHref: '#',
    repo: 'gelato/wftoracle5',
    tech: 'Web3 function',
    lastDeploy: '3h ago',
    location: 'United states',
    starred: true,
    active: true,
  },
  {
    name: 'Coingeckos price API to Oracle',
    href: '#',
    siteHref: '#',
    repoHref: '#',
    repo: 'gelato/wftoracle4',
    tech: 'Web3 function',
    lastDeploy: '3h ago',
    location: 'United states',
    starred: true,
    active: true,
  },
  {
    name: 'Coingeckos price API to Oracle',
    href: '#',
    siteHref: '#',
    repoHref: '#',
    repo: 'gelato/wftoracle3',
    tech: 'Web3 function',
    lastDeploy: '3h ago',
    location: 'United states',
    starred: true,
    active: true,
  },
  {
    name: 'Coingeckos price API to Oracle',
    href: '#',
    siteHref: '#',
    repoHref: '#',
    repo: 'gelato/wftoracle2',
    tech: 'Web3 function',
    lastDeploy: '3h ago',
    location: 'United states',
    starred: true,
    active: true,
  },
  {
    name: 'Coingeckos price API to Oracle',
    href: '#',
    siteHref: '#',
    repoHref: '#',
    repo: 'gelato/wftoracle1',
    tech: 'Web3 function',
    lastDeploy: '3h ago',
    location: 'United states',
    starred: true,
    active: true,
  },
  // More projects...
];

export { projects };
