/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as marketSol from "./Market.sol";
export type { marketSol };
import type * as nftSol from "./NFT.sol";
export type { nftSol };
